# 最小限のRuboCop設定（エラー回避）
AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable  # 新しいCopは無効化してエラー回避
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'config/**/*'

# 日本語コメント許可
Style/AsciiComments:
  Enabled: false

# 文字列リテラル（あまり厳格にしない）
Style/StringLiterals:
  Enabled: false

# 長い行を許可
Layout/LineLength:
  Enabled: false
