services:
  # Web Service (Rails App)
  - type: web
    name: bros-nuzlocke-tracker-web
    env: ruby
    plan: starter
    # Dockerを明示的に無効化
    runtime: ruby
    buildCommand: "bundle install && yarn install && ./bin/rails assets:precompile && ./bin/rails db:prepare"
    startCommand: "./bin/rails server -p $PORT -e $RAILS_ENV"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bros-nuzlocke-tracker-db
          property: connectionString
      # 個別のデータベース接続情報（フォールバック用）
      - key: DATABASE_HOST
        fromDatabase:
          name: bros-nuzlocke-tracker-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: bros-nuzlocke-tracker-db
          property: port
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: bros-nuzlocke-tracker-db
          property: password

databases:
  - name: bros-nuzlocke-tracker-db
    databaseName: bros_nuzlocke_tracker_production
    user: bros_nuzlocke_tracker
    plan: starter
    # PostgreSQLバージョンを明示指定
    ipAllowList: []
    plan: starter
